### ISSUE TITLE
Roadmap Ideas and Proposals [Discussion Thread]

### ISSUE THREAD

**Issue by itsjavi** [itsjavi/autotiler#1]
## Ideas

- [ ] Refactor code, splitting it better and using better patterns. React / Redux? + Some canvas lib?
- [x]  Auto-detect tile size when changing image.
- [ ] Drag and drop input image.
- [x] Generate output in same page.
- [x]  Export to Godot (Collisions and Bitmap).
- [ ] Zoom change.
- [ ] Preview Mode layers:
    - Grid
    - Grid split
    - Transparency
    - Collisions
    - Bitmask
- [ ] Edit Mode:
    - Edit collisions and bitmasks on the canvas (rects and triangles).
    - Edit Godot icon.
- [x] App exports for MacOS, Windows and Linux (Debian).
- [ ] Examples for 24-px and 32-px tiles.
- [ ] Support for Wang autotiles (reverse Blob to Wang)

## Unsupported

Not yet supported or not tested:

- [ ] Isometric tiles
- [ ] Non top-down tilesets
- [ ] Exporting to other game engines (Unity, Game Maker Studio)

**Comment by yuyutsupoudel** [comment]
One feature i would like to have is ability to choose individual tile files rather than whole tile sets. This could take a lot of time to implement, however it would be worth it to do so. 
![Something like this](https://user-images.githubusercontent.com/49397015/107164776-8a5af000-69d8-11eb-9007-59144e480a58.png)

**Comment by yuyutsupoudel** [comment]
One feature i would like to have is ability to choose individual tile files rather than whole tile sets. This could take a lot of time to implement, however it would be worth it to do so. This feature will allow user to create different tiles files for same tile and implement them easily rather than creating while tileset image file. Such as different grass texture, different dirt but same grass etc.
![Something like this](https://user-images.githubusercontent.com/49397015/107164880-f4739500-69d8-11eb-9333-4320ee33c9e3.gif)

**Comment by itsjavi** [comment]
@yuyutsupoudel it's a good Idea, I could Implement a drag an drop system to place the tiles in every cell, flip them, etc.
But yes, it requires a rework of the project. 

If we switch to react and convert this into a browser web app things may become easier.

**Comment by yuyutsupoudel** [comment]
@itsjavi honestly speaking, with out this feature, this project is like person with one broken leg. This is probably one of the game changing feature of this project. 
Wish i could contribute lol.

**Comment by itsjavi** [comment]
@yuyutsupoudel I know, but that's the idea of having it public and opensource. Everyone can make it better :)
